"""Parsers for humanitas.lt — CMS Made Simple + Products module.

The site's published sitemap.xml is unusable (it leaks the dev
hostname `humanitas.lt.kikilis.serveriai.lt` and uses the wrong
category slug `/produktas/visos-knygos/...` instead of production's
`/produktas/visos-kategorijos/...`). Instead, the discover spider
hits the catalogue index at
`/produktai/?m575a2product_limit=N` and we parse all product anchors
from the rendered HTML — one GET returns the entire catalogue
(~17 500 products in ~60 MB at limit=20000).

Field source on the product page:

  * `<title>{title} - Humanitas</title>` — title (suffix stripped).
  * `<meta property="og:image" content="...">` — cover URL.
  * `<meta property="og:description" content="...">` — full text.
  * `<div class="cart-container" data-product-id="189415">` — sku.
  * `<div class="full-price">…15.90 €</div>` — list price.
  * `<div class="cart-price"><div class="price-container">
       <div class="discount">15.10 €</div>  ← final price
       <div class="price">15.90 €</div>     ← pre-discount
     </div></div>`
  * `<div class="book-info">
       <b>ISBN:</b> 9786094802966 <br>
       <b>Autorius:</b> Loreta Tamulaitienė <br>
       <b>Leidimo metai:</b> 2022 <br>
       <b>Leidėjas:</b> Lietuvos rašytojų sąjungos leidykla <br>
       <b>Puslapių skaičius:</b> 344 <br>
       <b>Leidinio kalba:</b> Lietuvių <br>
       <b>Formatas:</b> Kieti viršeliai <br>
     </div>`
  * Out-of-stock signal: JS sets `out_of_stock = 'Likutis nepakankamas';`
    and the cart button is hidden — there is no plain HTML class on the
    product header. We approximate by scanning the rendered page for the
    `Likutis nepakankamas` substring near the cart container.

Coverage caveat (verified on the 2026-05-07 recon): some products
(legacy imports / accessories) lack the `<div class="book-info">`
block entirely. The parser tolerates this and emits the row with what
it can scrape; downstream classification falls back to the title-based
heuristics in vaga's classifier.
"""

from __future__ import annotations

import contextlib
import html as html_module
import re
from typing import Any, cast

from book_scraper.isbn import is_valid_isbn, normalize_isbn
from book_scraper.spiders.cover_type import format_from_cover_type
from book_scraper.spiders.parser_types import CategoryPageResult, ProductPageResult
from book_scraper.spiders.vaga.parsers import (
    classify_book_product,
    infer_shop_book_type,
)

# Anchors on the catalogue index. The href set is generated by the
# CMSMS Products module's card template. Product cards render as
# `<a class="book-item" href="...">` with the href in one of two
# shapes:
#
#   - Absolute on the homepage swiper:
#       https://www.humanitas.lt/produktas/<category-tree>/<slug>/
#   - Relative on paginated category pages, with the parent page's
#     `cntnt01page` echoed back into the query string:
#       /produktas/<category-tree>/<slug>/?cntnt01page=4
#
# We accept both, drop any query string (`cntnt01page` is a
# pagination-state marker, not part of the product identity), and
# coerce relative URLs to absolute.
_PRODUCT_ANCHOR_RE = re.compile(
    # Match any `<a …>` whose attributes include both
    # `class="…book-item…"` and `href="…"`, in either order.
    r'<a\b(?=[^>]*\bclass="[^"]*\bbook-item\b[^"]*")[^>]*\bhref="([^"]+)"',
    re.I,
)
_BASE_URL = "https://www.humanitas.lt"

# Language gate. Same source-of-truth as pegasas: parser-level filter
# on `Leidinio kalba` is the only reliable language signal because
# humanitas's category tree mixes LT and EN books under the same LT-
# named branches (e.g. `/produktas/visos-kategorijos/...` carries both
# `Lietuvių` and `Anglų` titles). Items where the field is absent fall
# through (~legacy imports without rich metadata) so we don't lose
# legitimate LT books just because the field wasn't populated.
_LANG_LITHUANIAN = "Lietuvių"

# Strip the ` - Humanitas` suffix Yoast/CMSMS appends to every <title>.
_TITLE_SUFFIX_RE = re.compile(r"\s*-\s*Humanitas\s*$", re.I)

# `<b>Label:?</b> Value <br>` rows inside `<div class="book-info">`.
# We allow the colon to be optional and the `<b>` tag to span
# whitespace — the rendered HTML wraps long labels onto multiple lines
# which puts the colon outside the `<b>` element on a separate line.
_BOOK_INFO_BLOCK_RE = re.compile(
    r'<div\s+class="book-info">(.*?)</div>',
    re.S | re.I,
)
_BOOK_INFO_ROW_RE = re.compile(
    r"<b>\s*([^<]+?)\s*:?\s*</b>\s*([^<]+?)\s*(?:<br|<b>|</div>)",
    re.S | re.I,
)


def _unescape(value: str | None) -> str | None:
    if value is None:
        return None
    cleaned = html_module.unescape(value)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned or None


def _meta_content(html: str, prop: str) -> str | None:
    """Read the `content` attribute of a `<meta property="..."> ` tag."""
    pat = (
        rf'<meta[^>]+property=["\']{re.escape(prop)}["\'][^>]+content=["\']'
        r'([^"\']*)["\']'
    )
    m = re.search(pat, html, re.I)
    return _unescape(m.group(1)) if m else None


def _extract_book_info(html: str) -> dict[str, str]:
    """Return a label→value map of all `<b>Label:</b> Value <br>` rows."""
    block = _BOOK_INFO_BLOCK_RE.search(html)
    if not block:
        return {}
    rows = _BOOK_INFO_ROW_RE.findall(block.group(1))
    out: dict[str, str] = {}
    for raw_label, raw_value in rows:
        label = _unescape(raw_label) or ""
        # Strip a trailing ':' that survives because the regex marks it
        # optional — easier than threading it through the regex.
        label = label.rstrip(":").strip()
        value = _unescape(raw_value)
        if label and value:
            out[label] = value
    return out


_PRICE_RE = re.compile(r"([\d ]+[.,]\d+)\s*€")

# Drop `<script>…</script>` blocks before the OOS-text sniff. The
# template inlines `var out_of_stock = 'Likutis nepakankamas';` on
# every product page, which would otherwise false-positive every
# in-stock listing as out of stock.
_SCRIPT_BLOCK_RE = re.compile(r"<script\b.*?</script>", re.S | re.I)


def _parse_price(raw: str | None) -> str | None:
    """Normalise a Lithuanian price (`1 234,56 €`, `15.10 €`) to `1234.56`."""
    if raw is None:
        return None
    m = _PRICE_RE.search(raw)
    if not m:
        return None
    value = m.group(1).replace(" ", "").replace(",", ".")
    return value or None


def _extract_price_pair(html: str) -> tuple[str | None, str | None, bool]:
    """Return ``(price, price_original, in_stock)`` from the cart block.

    The cart container is the canonical place for both numbers — the
    "Pilna kaina" banner is sometimes rendered without the discounted
    cart price (out-of-stock listings, pre-orders), and reading from the
    cart block keeps the two numbers paired even when only one is
    present.
    """
    cart_m = re.search(
        r'<div\s+class="cart-container"[^>]*>(.*?)</div>\s*</div>\s*</div>',
        html,
        re.S | re.I,
    )
    section = cart_m.group(0) if cart_m else html

    price = None
    price_original = None
    final_m = re.search(
        r'<div\s+class="price-container">.*?<div\s+class="discount">'
        r"\s*([^<]+)</div>\s*<div\s+class=\"price\">\s*([^<]+)</div>",
        section,
        re.S | re.I,
    )
    if final_m:
        price = _parse_price(final_m.group(1))
        price_original = _parse_price(final_m.group(2))

    if price is None:
        # Some listings omit the .price-container split and just print
        # one price under .cart-price (e.g. items where the flat 5%
        # online discount doesn't apply).
        single_m = re.search(
            r'<div\s+class="cart-price".*?(?:<div\s+class="label">[^<]*</div>)?'
            r"\s*([\d ]+[.,]\d+\s*€)",
            section,
            re.S | re.I,
        )
        if single_m:
            price = _parse_price(single_m.group(1))

    if price_original is None:
        full_m = re.search(
            r'<div\s+class="full-price"[^>]*>.*?<div\s+class="label">[^<]*</div>'
            r"\s*([\d ]+[.,]\d+\s*€)",
            html,
            re.S | re.I,
        )
        if full_m:
            price_original = _parse_price(full_m.group(1))

    if price is None and price_original is not None:
        price = price_original

    # `prices.in_stock` is NOT NULL in the schema, so we always emit a
    # boolean. Default to True (the live shop's overwhelming majority
    # of listings are in stock); flip to False when visible HTML
    # carries the "Likutis nepakankamas" (insufficient stock) notice
    # humanitas renders for OOS listings.
    #
    # We scan visible HTML only — the page also assigns
    # `var out_of_stock = 'Likutis nepakankamas';` inside a top-level
    # <script> on every product, so a naive substring check on the
    # raw response would mark every book OOS.
    visible = _SCRIPT_BLOCK_RE.sub("", html)
    in_stock: bool = "likutis nepakankamas" not in visible.lower()
    return price, price_original, in_stock


def parse_sitemap_urls(html: str) -> list[str]:
    """Extract every product URL from a catalogue index / category page.

    The discover spider calls this regardless of the source's content
    type — the name reflects the strategy slot, not the response
    format. For humanitas the "sitemap URL" is the paginated catalogue
    root `/produktai/visos-kategorijos/?m575a2product_limit=5000`,
    which renders an HTML page full of `<a class="book-item" ...>`
    cards. Duplicates are de-duplicated downstream so we just emit
    everything we recognise.
    """
    out: list[str] = []
    for raw in _PRODUCT_ANCHOR_RE.findall(html):
        # Strip the `cntnt01page=N` query string the CMSMS Products
        # module echoes onto every paginated card. The product is the
        # same regardless of which result page it appeared on.
        href = raw.split("?", 1)[0].split("#", 1)[0].strip().rstrip("/")
        if not href:
            continue
        if href.startswith("//"):
            href = "https:" + href
        elif href.startswith("/"):
            href = _BASE_URL + href
        if not href.startswith(_BASE_URL + "/produktas/"):
            continue
        out.append(href)
    return out


# Each book-item card on the listing page renders in roughly this
# shape:
#
#   <a class="book-item" href="/produktas/<...>/<slug>/?cntnt01page=1">
#     <div class="photo">
#       <img src="https://www.humanitas.lt/uploads/_CGSmartImage/<slug>_<hash>.webp">
#       <div class="discount-amount">-5%</div>     ← optional
#     </div>
#     <div class="author">David Markson</div>
#     <div class="title">Wittgensteino meilužė</div>
#     <div class="price">
#       <div class="normal">
#         <div class="price-container">
#           <div class="discount">14.25 €</div>    ← final price
#           <div class="price">15.00 €</div>       ← pre-discount
#         </div>
#       </div>
#     </div>
#     <div class="price-discount-info">5 % nuolaida perkant internetu</div>
#   </a>
#
# Live category listing pages sometimes include inner <a> tags inside
# cards (e.g. a wishlist or "Add to cart" anchor).  Using a non-greedy
# `.*?</a>` regex to extract the card body terminates at the *first*
# </a> — which is the inner anchor's close tag when it appears before
# the title/author divs — and silently drops all card metadata.
#
# We avoid this entirely by matching only the *opening* tag of each
# card and slicing the HTML between consecutive card openings.  The
# body for card N is `html[opening_N.end : opening_N+1.start]`.  This
# is immune to nested anchors and missing close tags, and captures the
# full title/author/price content regardless of card structure.
_CARD_OPENING_RE = re.compile(
    r'<a\b(?=[^>]*\bclass="[^"]*\bbook-item\b[^"]*")[^>]*\bhref="([^"]+)"[^>]*>',
    re.S | re.I,
)
_CARD_TITLE_RE = re.compile(
    r'<div\s+class="title"[^>]*>\s*([^<]+?)\s*</div>', re.I
)
_CARD_AUTHOR_RE = re.compile(
    r'<div\s+class="author"[^>]*>\s*([^<]+?)\s*</div>', re.I
)
_CARD_PRICE_PAIR_RE = re.compile(
    r'<div\s+class="price-container"[^>]*>\s*'
    r'<div\s+class="discount"[^>]*>\s*([^<]+?)\s*</div>\s*'
    r'<div\s+class="price"[^>]*>\s*([^<]+?)\s*</div>',
    re.S | re.I,
)
# When there's no online discount, only one price renders inside the
# .price block (no .price-container wrapper).
_CARD_SINGLE_PRICE_RE = re.compile(
    r'<div\s+class="price"[^>]*>\s*([\d ]+[.,]\d+\s*€)\s*</div>', re.I
)
_CARD_IMG_RE = re.compile(
    r'<img\s[^>]*\bsrc="([^"]+)"', re.I
)


def _parse_card(href: str, body: str) -> dict[str, Any] | None:
    """Extract per-card fields from one `<a class="book-item">` block.

    Returns ``None`` for anchors that don't look like a real book card
    (e.g. footer/menu anchors that happen to share the class name) so
    the caller can drop them. Title is the minimum signal — without
    it the card carries no useful data.
    """
    cleaned = href.split("?", 1)[0].split("#", 1)[0].strip().rstrip("/")
    if not cleaned:
        return None
    if cleaned.startswith("//"):
        cleaned = "https:" + cleaned
    elif cleaned.startswith("/"):
        cleaned = _BASE_URL + cleaned
    if not cleaned.startswith(_BASE_URL + "/produktas/"):
        return None

    title_m = _CARD_TITLE_RE.search(body)
    title = _unescape(title_m.group(1)) if title_m else None
    if not title:
        # Anchor styled as `book-item` but no .title block — not a
        # product card (e.g. a navigation tile).
        return {"url": cleaned}

    author_m = _CARD_AUTHOR_RE.search(body)
    author = _unescape(author_m.group(1)) if author_m else None

    price = price_original = None
    pair_m = _CARD_PRICE_PAIR_RE.search(body)
    if pair_m:
        price = _parse_price(pair_m.group(1))
        price_original = _parse_price(pair_m.group(2))
    else:
        single_m = _CARD_SINGLE_PRICE_RE.search(body)
        if single_m:
            price = _parse_price(single_m.group(1))

    image_url = None
    img_m = _CARD_IMG_RE.search(body)
    if img_m:
        image_url = img_m.group(1)

    return {
        "url": cleaned,
        "title": title,
        "author": author,
        "price": price,
        "price_original": price_original,
        "image_url": image_url,
        # Catalogue cards don't carry a stock signal — humanitas hides
        # OOS items from the listing entirely. Default to in-stock so
        # the pipeline's `prices.in_stock` (NOT NULL) gets a sensible
        # value; the scan path will overwrite this when it visits the
        # detail page if the book has since gone OOS.
        "in_stock": True,
    }


def parse_category_page(html: str) -> CategoryPageResult:
    """Extract per-card products from a humanitas catalogue listing page.

    With the LT-language server-side filter
    (``m575a2filt_leidimo_kalba=Lithuanian``) the listing returns only
    Lithuanian books, ~5 000 of them, in a single FlareSolverr round
    trip at ``m575a2product_limit=5000`` (~17 s wall time). Each
    `<a class="book-item">` card already carries title, author, final
    price, original price, and image URL — everything needed for a
    `Price` row. The detail page is still required for ISBN / year /
    pages / format / publisher (static metadata) but only on first
    sight, not on every weekly price refresh.

    Pagination is unreliable with the language filter: pages 1 and 2
    overlap by ~99 % at any limit (CMSMS quirk). We rely on the
    discover spider's standard "stop when a page returns 0 products"
    behaviour and a low ``max_pages`` safety cap in the TOML — page 2
    typically yields ~20 stragglers before page 3 returns empty.

    Card body extraction uses ``_CARD_OPENING_RE`` to locate the *start*
    of each `<a class="book-item">` tag; the body for card N is the
    slice of HTML from the end of opening N to the start of opening N+1.
    This is robust against nested inner `<a>` tags (e.g. wishlist or
    "Add to cart" buttons) that would otherwise cause the old non-greedy
    `.*?</a>` approach to terminate the body capture early and silently
    drop title/author/price data.
    """
    products: list[dict[str, Any]] = []
    seen: set[str] = set()
    openings = list(_CARD_OPENING_RE.finditer(html))
    for i, m in enumerate(openings):
        body_start = m.end()
        body_end = openings[i + 1].start() if i + 1 < len(openings) else len(html)
        product = _parse_card(m.group(1), html[body_start:body_end])
        if product is None:
            continue
        url = product["url"]
        if url in seen:
            continue
        seen.add(url)
        products.append(product)
    return {"products": products, "total": None}


def parse_product_page(html: str) -> ProductPageResult:
    """Parse a humanitas.lt product page HTML response.

    Tolerates the missing-`<div class="book-info">` case (verified on
    one of the two recon samples) by falling back to OG metadata only.
    """
    data: dict[str, object] = {
        "title": None,
        "description": None,
        "price": None,
        "price_original": None,
        "in_stock": None,
        "isbn": None,
        "sku": None,
        "publisher": None,
        "image_url": None,
        "categories": [],
        "year": None,
        "pages": None,
        "author": None,
        "cover_type": None,
        "format": None,
        "duration": None,
        "narrator": None,
        "translator": None,
        "schema_types": [],
        "is_book_product": False,
        "book_score": 0,
        "book_score_reasons": [],
        "type": "book",
        "planned_availability_date": None,
        "rating": None,
        "review_count": None,
    }

    # Title — strip the trailing " - Humanitas" suffix.
    og_title = _meta_content(html, "og:title")
    raw_title_m = re.search(r"<title>([^<]*)</title>", html, re.S | re.I)
    raw_title = _unescape(raw_title_m.group(1)) if raw_title_m else None
    title = og_title or (
        _TITLE_SUFFIX_RE.sub("", raw_title) if raw_title else None
    )
    data["title"] = title

    # OG description / image.
    description = _meta_content(html, "og:description")
    if description:
        data["description"] = description
    image_url = _meta_content(html, "og:image")
    if image_url:
        data["image_url"] = image_url

    # Internal product id from the cart container — used as our SKU.
    sku_m = re.search(r'data-product-id="([^"]+)"', html)
    if sku_m:
        data["sku"] = sku_m.group(1)

    # Price / stock from the cart block.
    price, price_original, in_stock = _extract_price_pair(html)
    data["price"] = price
    data["price_original"] = price_original
    data["in_stock"] = in_stock

    # `<div class="book-info">` rows — the rich block. May be absent.
    info = _extract_book_info(html)
    if info:
        isbn_raw = info.get("ISBN")
        if isbn_raw:
            isbn = normalize_isbn(isbn_raw)
            # `is_valid_isbn` accepts both ISBN-10 (e.g. older LT books
            # with the `9986…` country prefix from pre-2007) and
            # ISBN-13 (978/979 Bookland), with a real checksum check.
            # Generic non-book GTINs (sticker kits, puzzles) fail the
            # checksum + prefix gate and are silently dropped.
            if is_valid_isbn(isbn):
                data["isbn"] = isbn
        if (author := info.get("Autorius")) is not None:
            data["author"] = author
        if (publisher := info.get("Leidėjas")) is not None:
            data["publisher"] = publisher
        # Guard against shops that occasionally use Leidykla too —
        # not seen on humanitas yet but the cost is one dict lookup.
        if data["publisher"] is None and (alt := info.get("Leidykla")) is not None:
            data["publisher"] = alt
        if (year_raw := info.get("Leidimo metai")) is not None:
            with contextlib.suppress(ValueError):
                data["year"] = int(year_raw)
        if (pages_raw := info.get("Puslapių skaičius")) is not None:
            with contextlib.suppress(ValueError):
                data["pages"] = int(pages_raw)
        if (cover := info.get("Formatas")) is not None:
            # `Formatas:` on humanitas overloads two unrelated fields:
            # the cover binding (`Kieti viršeliai` / `Minkšti viršeliai`)
            # and physical dimensions in many shapes:
            #   `240 x 202`, `288 x 243`, `9.25×7.5`, `170 × 230 mm`,
            #   `23,5x18 cm.`, `198×129`, `19.6×12.7`. Skip any value
            # that looks like dimensions (number, separator, number)
            # and the "pasirinkite" placeholder ("choose" — empty
            # selector default), so we don't pollute `format` with
            # values like "288 x 243".
            looks_like_dimensions = bool(
                re.match(
                    r"^\s*\d+(?:[.,]\d+)?\s*[xX×]\s*\d+",
                    cover,
                )
            )
            placeholder = cover.strip().lower() == "pasirinkite"
            if not looks_like_dimensions and not placeholder:
                data["cover_type"] = cover
                data["format"] = format_from_cover_type(cover)
            elif looks_like_dimensions:
                # Surface dimensions verbatim under properties so they
                # aren't silently dropped — useful for cross-shop
                # matching even though we don't have a top-level
                # ShopBookItem field for them.
                props = data.get("properties")
                if not isinstance(props, dict):
                    props = {}
                props["dimensions"] = cover
                data["properties"] = props
        if (dimensions := info.get("Matmenys")) is not None:
            props = data.get("properties")
            if not isinstance(props, dict):
                props = {}
            props["dimensions"] = dimensions
            data["properties"] = props
        if (translator := info.get("Vertėjas")) is not None:
            data["translator"] = translator

        # Use Leidinio kalba as the LT-language gate. Stored verbatim
        # on `properties.language` for the pipeline to pick up; we
        # don't add it as a top-level field because the existing item
        # schema doesn't have one for it.
        language = info.get("Leidinio kalba")
        if language:
            # Surface as a property so the language can be filtered on
            # downstream without altering the ShopBookItem schema.
            props = data.get("properties")
            if not isinstance(props, dict):
                props = {}
            props["language"] = language
            data["properties"] = props

    classification = classify_book_product(data)
    data["is_book_product"] = classification.is_book_product
    data["book_score"] = classification.score
    data["book_score_reasons"] = classification.reasons
    data["type"] = infer_shop_book_type(data)

    # LT-only language gate. After classification so the `book_score`
    # still reflects the real signal mix; we just override
    # `is_book_product` to False so the scan spider marks the URL as
    # `non_product` and skips the shop_books insert. Mirrors pegasas's
    # `_graphql_item_to_product` returning None for non-LT items.
    # When the language attribute is missing we let the row through —
    # losing legacy imports without metadata costs us legitimate LT
    # books (same lesson as pegasas, ~1 % of catalogue).
    properties = data.get("properties")
    detected_language = (
        properties.get("language") if isinstance(properties, dict) else None
    )
    if (
        isinstance(detected_language, str)
        and detected_language.strip()
        and detected_language.strip() != _LANG_LITHUANIAN
    ):
        data["is_book_product"] = False
        reasons = data.get("book_score_reasons")
        if isinstance(reasons, list):
            reasons.append(
                {"key": "blocked_non_lt_language", "points": 0,
                 "language": detected_language.strip()}
            )

    # Properties dict isn't part of ProductPageResult; the discover/
    # scan spiders inspect top-level keys (`pages`, `cover_type`, …)
    # plus a parser-supplied `properties` dict if present. We surface
    # `language` via `properties` (set above) so downstream can read
    # it without changing the item schema.
    return cast(ProductPageResult, data)


def parse_index_page(html: str) -> list[dict[str, Any]]:
    """Convenience for tests: return ``[{ 'url': str }, …]`` for index URLs.

    The discover spider only needs the URL list (via
    `parse_sitemap_urls`); this helper exists so tests can assert the
    same set with a slightly richer shape.
    """
    return [{"url": url} for url in parse_sitemap_urls(html)]
