import globals from "globals";

export default [
    {
        files: ["public/static/hifi/**/*.jsx", "tools/**/*.mjs"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            parserOptions: { ecmaFeatures: { jsx: true } },
            globals: {
                ...globals.browser,
                ...globals.node,
                React: "readonly",
                ReactDOM: "readonly",
            },
        },
        rules: {
            "constructor-super": "error",
            "for-direction": "error",
            "getter-return": "error",
            "no-async-promise-executor": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-const-assign": "error",
            "no-debugger": "error",
            "no-dupe-args": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-func-assign": "error",
            "no-import-assign": "error",
            "no-loss-of-precision": "error",
            "no-new-native-nonconstructor": "error",
            "no-obj-calls": "error",
            "no-promise-executor-return": "error",
            "no-self-assign": "error",
            "no-setter-return": "error",
            "no-sparse-arrays": "error",
            "no-this-before-super": "error",
            "no-undef": "off",
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "no-unreachable-loop": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-labels": "error",
            "no-unused-private-class-members": "error",
            "no-unused-vars": "off",
            "no-useless-backreference": "error",
            "no-useless-catch": "error",
            "no-useless-escape": "error",
            "no-with": "error",
            "require-yield": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
        },
    },
];
