<?php

declare(strict_types=1);

namespace BookScraper\Tests;

use BookScraper\UrlUtils;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Canonical URL form backs two unique constraints, so PHP and Python must
 * agree exactly. The corpus in golden/urls.json mixes hand-picked edge
 * cases with real production URLs and is regenerated by
 * tools/dump_url_golden.py.
 */
final class UrlUtilsDifferentialTest extends TestCase
{
    /** @return iterable<string, array{0: string, 1: string}> */
    public static function urls(): iterable
    {
        $golden = json_decode(
            (string) file_get_contents(__DIR__ . '/golden/urls.json'),
            true,
            flags: JSON_THROW_ON_ERROR
        );

        foreach ($golden as $input => $expected) {
            yield $input => [(string) $input, (string) $expected];
        }
    }

    #[DataProvider('urls')]
    public function test_matches_python(string $input, string $expected): void
    {
        self::assertSame($expected, UrlUtils::normalize($input));
    }
}
