"""add pid to scrape_runs

Revision ID: 130fcef8e7eb
Revises: 3a5148ef9025
Create Date: 2026-04-10 22:04:42.544454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130fcef8e7eb'
down_revision: Union[str, Sequence[str], None] = '3a5148ef9025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'pid')
    # ### end Alembic commands ###

