"""add validation_issues table

Revision ID: 2ee38722fb89
Revises: 39c70b6e751e
Create Date: 2026-04-10 16:28:32.919468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee38722fb89'
down_revision: Union[str, Sequence[str], None] = '39c70b6e751e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_scrape_run_id'), 'validation_issues', ['scrape_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issues_scrape_run_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    # ### end Alembic commands ###

