"""add run stats columns

Revision ID: 39c70b6e751e
Revises: c168f8c9395f
Create Date: 2026-04-06 18:14:19.708274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c70b6e751e'
down_revision: Union[str, Sequence[str], None] = 'c168f8c9395f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('items_added', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_runs', sa.Column('items_updated', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_runs', sa.Column('errors_4xx', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_runs', sa.Column('errors_5xx', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_runs', sa.Column('error_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'error_count')
    op.drop_column('scrape_runs', 'errors_5xx')
    op.drop_column('scrape_runs', 'errors_4xx')
    op.drop_column('scrape_runs', 'items_updated')
    op.drop_column('scrape_runs', 'items_added')
    # ### end Alembic commands ###

