"""add last_heartbeat to scrape_runs

Revision ID: 3a5148ef9025
Revises: 2ee38722fb89
Create Date: 2026-04-10 22:00:21.141590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5148ef9025'
down_revision: Union[str, Sequence[str], None] = '2ee38722fb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'last_heartbeat')
    # ### end Alembic commands ###

