"""add format, duration, narrator, translator to listings

Revision ID: 47a56ea82802
Revises: e6ccc5193517
Create Date: 2026-04-05 23:43:47.927616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a56ea82802'
down_revision: Union[str, Sequence[str], None] = 'e6ccc5193517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('format', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('narrator', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('translator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'translator')
    op.drop_column('listings', 'narrator')
    op.drop_column('listings', 'duration')
    op.drop_column('listings', 'format')
    # ### end Alembic commands ###

