"""add scrape_run_id to prices table

Revision ID: a29261e555de
Revises: c936ec5c4216
Create Date: 2026-04-14 20:14:58.833577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29261e555de'
down_revision: Union[str, Sequence[str], None] = 'c936ec5c4216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('scrape_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prices_scrape_run_id'), 'prices', ['scrape_run_id'], unique=False)
    op.create_foreign_key(None, 'prices', 'scrape_runs', ['scrape_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.drop_index(op.f('ix_prices_scrape_run_id'), table_name='prices')
    op.drop_column('prices', 'scrape_run_id')
    # ### end Alembic commands ###

