"""add metadata fields to listings

Revision ID: bf22b2c5b984
Revises: 9d044f7a03d6
Create Date: 2026-04-05 23:07:27.702117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf22b2c5b984'
down_revision: Union[str, Sequence[str], None] = '9d044f7a03d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('cover_type', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'categories')
    op.drop_column('listings', 'description')
    op.drop_column('listings', 'cover_type')
    op.drop_column('listings', 'pages')
    op.drop_column('listings', 'year')
    op.drop_column('listings', 'publisher')
    # ### end Alembic commands ###

