"""add discovered_urls and scrape_runs tables

Revision ID: c168f8c9395f
Revises: d34132e979d1
Create Date: 2026-04-06 08:08:38.081438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c168f8c9395f'
down_revision: Union[str, Sequence[str], None] = 'd34132e979d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('sitemap', 'category', 'full_crawl', name='discovery_source'), nullable=False),
    sa.Column('url_type', sa.Enum('unknown', 'product', 'non_product', name='url_type'), server_default='unknown', nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'url', name='uq_discovered_urls_shop_url')
    )
    op.create_index('ix_discovered_urls_shop_type_fail', 'discovered_urls', ['shop_id', 'url_type', 'fail_count'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('discover_sitemap', 'discover_categories', 'discover_full_crawl', 'scan', name='scrape_phase'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='scrape_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urls_total', sa.Integer(), nullable=True),
    sa.Column('urls_processed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_runs')
    op.drop_index('ix_discovered_urls_shop_type_fail', table_name='discovered_urls')
    op.drop_table('discovered_urls')
    sa.Enum(name='scrape_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='scrape_phase').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='url_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='discovery_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

