"""add listing_changes table

Revision ID: c936ec5c4216
Revises: dcda8e749b1a
Create Date: 2026-04-11 05:18:39.256394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c936ec5c4216'
down_revision: Union[str, Sequence[str], None] = 'dcda8e749b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_changes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_changes_listing_id'), 'listing_changes', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_changes_listing_id'), table_name='listing_changes')
    op.drop_table('listing_changes')
    # ### end Alembic commands ###

