"""add last_run_id and last_run_action to listings

Revision ID: dcda8e749b1a
Revises: 130fcef8e7eb
Create Date: 2026-04-10 22:40:54.365188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcda8e749b1a'
down_revision: Union[str, Sequence[str], None] = '130fcef8e7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('last_run_id', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('last_run_action', sa.String(), nullable=True))
    op.create_foreign_key(None, 'listings', 'scrape_runs', ['last_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'last_run_action')
    op.drop_column('listings', 'last_run_id')
    # ### end Alembic commands ###

