"""add sku to listings

Revision ID: f71a5796938e
Revises: bf22b2c5b984
Create Date: 2026-04-05 23:21:14.944670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71a5796938e'
down_revision: Union[str, Sequence[str], None] = 'bf22b2c5b984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('sku', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'sku')
    # ### end Alembic commands ###

