apiVersion: 1

deleteDatasources:
  - name: Postgres (book_scraper)
    orgId: 1

datasources:
  - name: Postgres (book_scraper)
    uid: postgres-bookscraper
    type: postgres
    access: proxy
    url: postgres:5432
    user: $GRAFANA_DB_USER
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      database: book_scraper
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false
