<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Concerns\HasSqlAlchemyDefaults;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Append-only: one row per scrape per shop_book. Never updated in place —
 * the price history is the product.
 *
 * `discount_pct` is a generated column; it is read-only here on purpose.
 *
 * @property int $id
 * @property int $shop_book_id
 * @property string $price
 * @property bool $in_stock
 */
final class Price extends Model
{
    protected $table = 'prices';

    public $timestamps = false;

    use HasSqlAlchemyDefaults;

    public const TIMESTAMP_DEFAULTS = ['scraped_at'];

    protected $fillable = [
        'shop_book_id', 'price', 'price_original', 'in_stock',
        'scraped_at', 'scrape_run_id',
    ];

    protected $casts = [
        'in_stock' => 'boolean',
        'scraped_at' => 'datetime',
    ];

    /** Generated by Postgres — writing it would fail the insert. */
    protected $guarded = ['discount_pct'];

    public function shopBook(): BelongsTo
    {
        return $this->belongsTo(ShopBook::class, 'shop_book_id');
    }
}
